[model]
attribute_encoder_type = 'text'
resnet_hidden_dim = 256
resnet_num_blocks = 8
exog_input_dim = 103
onehot_attr_input_dim = 336
mlp_hidden_dim = 256
qoi_dim = 1
text_encoder_name = 'distilbert-base-uncased'
text_freeze_encoder = false
text_finetune_only_specific_layers = true
continuous_head = 'mse'
ignore_attributes = false
timestamp_embedding_size = 32

[experiment]
module_name = 'resnet'
lr = 3e-4
batch_size = 256