[model]
attribute_encoder_type = 'text'
resnet_hidden_dim = 256
resnet_num_blocks = 8
exog_input_dim = 103
onehot_attr_input_dim = 336
mlp_hidden_dim = 256
qoi_dim = 1
text_encoder_name = 'bert-base-uncased'
text_freeze_encoder = false
text_finetune = false
continuous_head = 'mse'
ignore_attributes = false
timestamp_embedding_size = 32

[experiment]
module_name = 'resnet'
lr = 5e-5
batch_size = 256
max_train_steps = 200000
early_stopping_patience = 50
